# Generated by Django 6.0.1 on 2026-02-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_due_date'),
        ('customers', '0005_connectiontype_code_connectiontype_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='months_covered',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='subscription',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='advance_payment',
            field=models.ForeignKey(blank=True, help_text='Linked advance payment if paid from advance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='billing.advancepayment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('adjustment_from_advance', 'Adjustment from Advance'), ('other', 'Other')], max_length=50),
        ),
    ]
