# Generated by Django 6.0.1 on 2026-01-14 22:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_billing_type'),
        ('mikrotik', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('billing_day', models.IntegerField(help_text='Day of month for billing (1-31)', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('mikrotik_username', models.CharField(help_text='PPPoE username for MikroTik', max_length=100, unique=True)),
                ('mikrotik_password', models.CharField(help_text='PPPoE password for MikroTik', max_length=100)),
                ('mikrotik_user_id', models.CharField(blank=True, help_text='MikroTik PPPoE user ID', max_length=50, null=True)),
                ('is_synced_to_mikrotik', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('connection_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='One-time connection fee', max_digits=10)),
                ('reconnection_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Reconnection fee after suspension', max_digits=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='mikrotik.package')),
                ('router', models.ForeignKey(blank=True, help_text='Assigned MikroTik router', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='mikrotik.mikrotikrouter')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('activated', 'Activated'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('package_changed', 'Package Changed'), ('router_changed', 'Router Changed')], max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_actions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscription.subscription')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription Histories',
                'db_table': 'subscription_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer'], name='subscriptio_custome_4251b9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_572d44_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['billing_day'], name='subscriptio_billing_e0bc0f_idx'),
        ),
    ]
