# Generated by Django 6.0.1 on 2026-01-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='framed_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Assigned IP Address from MikroTik', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Device MAC Address', max_length=17, null=True),
        ),
    ]
