# Generated by Django 6.0.1 on 2026-02-01 01:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_apscheduler', '0009_djangojobexecution_unique_job_executions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('job', models.OneToOneField(help_text='APScheduler job to configure', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='schedule_config', serialize=False, to='django_apscheduler.djangojob')),
                ('name', models.CharField(help_text='Human-readable name for the job', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this job does')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this job is enabled')),
                ('interval_value', models.IntegerField(default=1, help_text="Interval value (e.g., 5 for '5 minutes')", validators=[django.core.validators.MinValueValidator(1)])),
                ('interval_unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='minutes', help_text='Interval unit', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text='Cron expression (optional, overrides interval if set)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schedule Configuration',
                'verbose_name_plural': 'Schedule Configurations',
                'db_table': 'schedule_config',
                'ordering': ['job_id'],
            },
        ),
    ]
