# Generated by Django 6.0.1 on 2026-02-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='schedule_time',
            field=models.TimeField(blank=True, help_text='Time of day for daily schedules (e.g., 02:00 for 2 AM)', null=True),
        ),
    ]
