# Generated by Django 6.0.1 on 2026-02-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_scheduleconfig_interval_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleconfig',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scheduleconfig',
            name='name',
        ),
    ]
