# Generated by Django 6.0.1 on 2026-01-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikqueueprofile',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_profiles', to='mikrotik.package'),
        ),
    ]
