# Generated by Django 6.0.1 on 2026-02-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_scheduleconfig_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='interval_unit',
            field=models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='minutes', help_text='Interval unit', max_length=20),
        ),
    ]
