# Generated by Django 6.0.1 on 2026-01-14 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique zone code (e.g., MIR, GUL, DHK)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '01XXXXXXXXX'", regex='^01[3-9]\\d{8}$')])),
                ('alternative_phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '01XXXXXXXXX'", regex='^01[3-9]\\d{8}$')])),
                ('nid', models.CharField(blank=True, help_text='National ID Number', max_length=20, null=True)),
                ('address', models.TextField()),
                ('billing_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('free', 'Free')], default='residential', max_length=20)),
                ('connection_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('static_ip', 'Static IP'), ('hotspot', 'Hotspot')], default='pppoe', max_length=20)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address for binding (format: XX:XX:XX:XX:XX:XX)', max_length=17, null=True)),
                ('static_ip', models.GenericIPAddressField(blank=True, help_text='Static IP for business customers', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.zone')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='customers_custome_b85ebb_idx'), models.Index(fields=['phone'], name='customers_phone_91048b_idx'), models.Index(fields=['status'], name='customers_status_47bd31_idx'), models.Index(fields=['zone'], name='customers_zone_id_492dee_idx')],
            },
        ),
    ]
