# Generated by Django 6.0.1 on 2026-01-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_alternative_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('free', 'Free')], default='residential', max_length=20),
        ),
    ]
