# Generated by Django 6.0.1 on 2026-01-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_framed_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_start_month',
            field=models.DateField(blank=True, help_text='Month from which billing cycle starts (YYYY-MM-01 format)', null=True),
        ),
    ]
