# Generated by Django 6.0.1 on 2026-02-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_add_billing_start_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='mikrotik_profile_name',
            field=models.CharField(blank=True, help_text='MikroTik profile name (fetched from router)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='protocol',
            field=models.CharField(blank=True, choices=[('pppoe', 'PPPoE'), ('dhcp', 'DHCP'), ('hotspot', 'Hotspot'), ('static', 'Static IP')], help_text='Connection protocol', max_length=20, null=True),
        ),
    ]
