# Generated by Django 6.0.1 on 2026-02-01 17:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription_mikrotik_profile_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='connection_fee',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='reconnection_fee',
        ),
        migrations.CreateModel(
            name='ConnectionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee_type', models.CharField(choices=[('connection', 'New Connection Fee'), ('reconnection', 'Reconnection Fee'), ('other', 'Other Fee')], default='connection', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_connection_fees', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_fees', to='subscription.subscription')),
            ],
            options={
                'verbose_name': 'Connection Fee',
                'verbose_name_plural': 'Connection Fees',
                'db_table': 'connection_fees',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
