# Generated by Django 6.0.1 on 2026-02-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_subscription_connection_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionfee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='connectionfee',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
