# Generated by Django 6.0.1 on 2026-01-14 21:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alternative_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Alternative phone number', max_length=128, null=True, region='BD'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('business', 'Business'), ('vip', 'VIP')], default='residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number in international format', max_length=128, region='BD'),
        ),
    ]
