# Generated by Django 6.0.1 on 2026-02-02 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Connection Type',
                'verbose_name_plural': 'Connection Types',
                'db_table': 'connection_types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='connection_type',
            field=models.ForeignKey(blank=True, help_text='Type of connection (e.g., PPPoE, Optical Fiber)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.connectiontype'),
        ),
    ]
