# Generated by Django 6.0.1 on 2026-02-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_connectiontype_alter_customer_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontype',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code (e.g., PPPOE, STATIC)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='connectiontype',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
