# Generated by Django 6.0.1 on 2026-01-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bill',
            name='bills_due_dat_7854b3_idx',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
    ]
