# Generated by Django 6.0.1 on 2026-01-14 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bandwidth_download', models.IntegerField(help_text='Download speed in Mbps', validators=[django.core.validators.MinValueValidator(1)])),
                ('bandwidth_upload', models.IntegerField(help_text='Upload speed in Mbps', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_days', models.IntegerField(default=30, help_text='Package validity in days')),
                ('description', models.TextField(blank=True, null=True)),
                ('mikrotik_queue_name', models.CharField(help_text='MikroTik queue profile name (e.g., home-10mbps)', max_length=100, unique=True)),
                ('burst_limit_download', models.IntegerField(blank=True, help_text='Burst download limit in Mbps (optional), Providing higher speed than the normal speed for a short period of time.', null=True)),
                ('burst_limit_upload', models.IntegerField(blank=True, help_text='Burst upload limit in Mbps (optional), Providing higher speed than the normal speed for a short period of time.', null=True)),
                ('burst_threshold_download', models.IntegerField(blank=True, help_text='Burst threshold download in Mbps (optional), The threshold at which the burst limit is activated.', null=True)),
                ('burst_threshold_upload', models.IntegerField(blank=True, help_text='Burst threshold upload in Mbps (optional), The threshold at which the burst limit is activated.', null=True)),
                ('burst_time', models.IntegerField(blank=True, help_text='Burst time in seconds (optional), The duration for which the burst limit is activated.', null=True)),
                ('priority', models.IntegerField(default=8, help_text='Queue priority (1-8, lower is higher priority), Lower value means higher priority.', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 'packages',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='MikroTikRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('api_port', models.IntegerField(default=8728)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(help_text='Router API password', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(blank=True, help_text='Assign router to specific zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mikrotik_routers', to='customers.zone')),
            ],
            options={
                'verbose_name': 'MikroTik Router',
                'verbose_name_plural': 'MikroTik Routers',
                'db_table': 'mikrotik_routers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MikroTikSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_queue', 'Create Queue'), ('update_queue', 'Update Queue'), ('delete_queue', 'Delete Queue'), ('create_user', 'Create PPPoE User'), ('update_user', 'Update PPPoE User'), ('delete_user', 'Delete PPPoE User'), ('enable_user', 'Enable User'), ('disable_user', 'Disable User')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('entity_type', models.CharField(help_text='e.g., queue, pppoe_user', max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='mikrotik.mikrotikrouter')),
            ],
            options={
                'verbose_name': 'MikroTik Sync Log',
                'verbose_name_plural': 'MikroTik Sync Logs',
                'db_table': 'mikrotik_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MikroTikQueueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mikrotik_queue_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_profiles', to='mikrotik.mikrotikrouter')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_profile', to='mikrotik.package')),
            ],
            options={
                'verbose_name': 'MikroTik Queue Profile',
                'verbose_name_plural': 'MikroTik Queue Profiles',
                'db_table': 'mikrotik_queue_profiles',
                'unique_together': {('package', 'router')},
            },
        ),
    ]
