# Generated by Django 6.0.1 on 2026-02-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0002_alter_mikrotikqueueprofile_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='bandwidth_download',
        ),
        migrations.RemoveField(
            model_name='package',
            name='bandwidth_upload',
        ),
        migrations.RemoveField(
            model_name='package',
            name='burst_limit_download',
        ),
        migrations.RemoveField(
            model_name='package',
            name='burst_limit_upload',
        ),
        migrations.RemoveField(
            model_name='package',
            name='burst_threshold_download',
        ),
        migrations.RemoveField(
            model_name='package',
            name='burst_threshold_upload',
        ),
        migrations.RemoveField(
            model_name='package',
            name='burst_time',
        ),
        migrations.RemoveField(
            model_name='package',
            name='mikrotik_queue_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='package',
            name='validity_days',
        ),
    ]
